### PR TITLE
Switch alert show/hide to a prop

### LINKED ISSUE #531: When closing an overlay drawer, the success message isn’t announced [Safari/VoiceOver]
After successfully completing a task in an overlay drawer, the drawer closes, and focus returns to the table. (#496) Unfortunately, the success message isn’t announced by VoiceOver, so there’s no indication that the transaction successfully completed.

Here’s a screen recording of this behavior:

https://github.com/user-attachments/assets/26ba9553-db1c-42d7-b96e-cfd65dc7a542

(No audio, sorry; couldn’t find a way to do that on macOS.)

_Can this task be done in one increment?_

Unknown; marking as research.

### Acceptance Criteria
- [ ] The drawer closes successfully
- [ ] The message is announced by VoiceOver

### PR DESCRIPTION
**Pull request by echappen**
## Changes proposed in this pull request:

- Switch `Alert` show-hiding to a prop (this ensures that the aria-live region in the Alert component is present on page load)

### Related issues

Closes #531 
Overrides #573 

### Submitter checklist

- [ ] Added logging is not capturing sensitive data and is set to an appropriate level (DEBUG vs INFO etc)
- [ ] Updated relevant documentation (README, ADRs, explainers, diagrams)

## Security considerations

None, UI refactor only

### CODE REVIEW

**Comment by beepdotgov** [comment]
@echappen Just to check, should I be seeing messages/alerts in `aria-live` regions on the Manage Users page?

(If I should be testing somewhere else, just let me know.)

**Comment by echappen** [comment]
@beepdotgov Yep, Alerts are now wrapped in aria-live regions (which are now present on page-load). So whatever text is in the alert should be the text read by the SR. You can trigger a success alerts by updating roles for any user on the Manage Users page.

**Comment by beepdotgov** [comment]
Ach, sorry — must’ve had something cached. I see the `role="status"` container now!

**Review by beepdotgov — APPROVED** [review]
Just want to say that I was able to update some permissions, and the success notification was successfully read out each time! _Exciting_ to see this fixed! 🎉

**Comment by echappen** [comment]
@beepdotgov Thank you for all your manual testing and collaboration on this!

**Comment by beepdotgov** [comment]
Thank _you_ for doing such thoughtful research on this, @echappen. I’ve learned a lot watching you work through this!

**Pull request merged**
